<?php

namespace Wanasni\TrajetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRepository extends EntityRepository
{

    public function MyFind($origine,$destination,$dates,$frequence){
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.origine LIKE :o')
            ->setParameter('o',$origine)
            ->andWhere('a.destination LIKE :d')
            ->setParameter('d',$destination)
            ->andWhere('a.date IN (:dates)')
            ->setParameter('dates',$dates)
            ->andWhere('a.freqeunce = :f')
            ->setParameter('f',$frequence)
        ;

        return $qb->getQuery()->getResult();
    }

}
