<?php

namespace Wanasni\TrajetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrixOptimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrixOptimalRepository extends EntityRepository
{
}
