<?php

namespace Wanasni\TrajetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends EntityRepository
{

    public function getTrajetById($id){
        $qb = $this->createQueryBuilder('t');
        $qb
            ->join('t.Origine', 'o')
            ->addSelect('o')
            ->join('t.Destination', 'd')
            ->addSelect('d')
            ->join('t.Segments', 's')
            ->addSelect('s')
            ->join('t.datesAller', 'da')
            ->addSelect('da')
            ->join('t.datesRetour', 'dr')
            ->addSelect('dr')
            ->where('t.id = :id')
            ->setParameter('id',$id)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }



    public function SearchByOrigineAndDestination($depart,$arrive,$date){
        $qb = $this->createQueryBuilder('t');

        $qb->join('t.Origine', 'origine')
            ->join('t.Destination','destination')
            ->leftJoin('t.datesAller','datesAller')
            ->leftJoin('t.datesRetour','datesRetour')
            ->where('origine.lieu LIKE :depart')
            ->setParameter('depart', $depart)
            ->andWhere('destination.lieu LIKE :arrive')
            ->setParameter('arrive',$arrive)
            ->andWhere('datesAller.date = :date OR datesRetour.date = :date OR t.Date_Allet_unique= :date OR t.Date_Retour_unique= :date')
            ->setParameter('date', $date)
        ;


        return $qb->getQuery()->getResult();
    }

}
