<?php

namespace Wanasni\VehiculeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculeRepository extends EntityRepository
{


    public function getCar($id)
    {
        return $this->createQueryBuilder('v')
            ->addSelect('v.trajets','t')
            ->where('v.id = :id')
            ->setParameter('id',$id);
    }


}
