<?php

namespace Wanasni\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Wanasni\UserBundle\Entity\User;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{


    public function nbUnreadNotification(User $user)
    {
        return $this->createQueryBuilder('n')
            ->select('COUNT(n)')
            ->where('n.lu = false')
            ->andWhere('n.user = :u')
            ->setParameter('u', $user)
            ->getQuery()
            ->getSingleScalarResult();

    }

}
